package automated_tests.tech.derbent.ui.automation;

import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.TestPropertySource;
import com.microsoft.playwright.Locator;

/** Test for CUser dynamic page - verifies that new users are created, saved, and appear in grid */
@SpringBootTest (webEnvironment = WebEnvironment.RANDOM_PORT, classes = tech.derbent.Application.class)
@TestPropertySource (properties = {
		"spring.datasource.url=jdbc:h2:mem:testdb", 
		"spring.datasource.username=sa", 
		"spring.datasource.password=", 
		"spring.datasource.driver-class-name=org.h2.Driver", 
		"spring.jpa.hibernate.ddl-auto=create-drop", 
		"server.port=0"
})
public class CUserDynamicPageTest extends CBaseUITest {

	private static final Logger LOGGER = LoggerFactory.getLogger(CUserDynamicPageTest.class);

	@Test
	public void testUserCreateSaveAndGrid() {
		LOGGER.info("=== Testing User Create, Save, and Grid Display ===");
		try {
			// Login
			loginToApplication("admin", "test123");
			wait_afterlogin();
			LOGGER.info("✅ Logged in successfully");
			
			// Navigate to Users view
			navigateToViewByText("Users");
			wait_1000();
			takeScreenshot("user-page-initial", false);
			LOGGER.info("✅ Navigated to Users view");
			
			// Get initial grid count
			Locator grid = page.locator("vaadin-grid").first();
			Locator gridCells = grid.locator("vaadin-grid-cell-content");
			int initialRowCount = gridCells.count();
			LOGGER.info("📊 Initial grid row count: {}", initialRowCount);
			
			// Click New button
			LOGGER.info("➕ Clicking New button");
			clickNew();
			wait_1000();
			takeScreenshot("user-after-new", false);
			
			// Check if form fields appeared and are populated
			Locator nameField = page.locator("vaadin-text-field").first();
			if (nameField.count() > 0) {
				String autoGeneratedName = nameField.inputValue();
				LOGGER.info("📝 Auto-generated name: {}", autoGeneratedName);
				
				if (autoGeneratedName != null && !autoGeneratedName.isEmpty()) {
					LOGGER.info("✅ Form populated with auto-generated name");
				} else {
					LOGGER.error("❌ BUG: Form field is empty after clicking New");
					takeScreenshot("user-bug-empty-after-new", true);
				}
			} else {
				LOGGER.error("❌ BUG: No form fields visible after clicking New");
				takeScreenshot("user-bug-no-fields", true);
			}
			
			// Modify name to make it unique
			String uniqueName = "TestUser" + System.currentTimeMillis();
			nameField.fill(uniqueName);
			wait_500();
			LOGGER.info("📝 Modified name to: {}", uniqueName);
			takeScreenshot("user-filled", false);
			
			// Save the user
			LOGGER.info("💾 Clicking Save button");
			clickSave();
			wait_2000(); // Wait for save operation
			takeScreenshot("user-after-save", false);
			
			// Check if grid was refreshed and new user appears
			wait_1000(); // Extra wait for grid refresh
			gridCells = grid.locator("vaadin-grid-cell-content");
			int finalRowCount = gridCells.count();
			LOGGER.info("📊 Final grid row count: {}", finalRowCount);
			
			if (finalRowCount > initialRowCount) {
				LOGGER.info("✅ SUCCESS: Grid updated with new user (count increased from {} to {})", initialRowCount, finalRowCount);
				
				// Verify the new user's name appears in grid
				String gridText = grid.innerText();
				if (gridText.contains(uniqueName)) {
					LOGGER.info("✅ SUCCESS: New user '{}' appears in grid", uniqueName);
				} else {
					LOGGER.error("❌ BUG: New user '{}' saved but not visible in grid", uniqueName);
					LOGGER.error("Grid content: {}", gridText);
					takeScreenshot("user-bug-not-in-grid", true);
				}
			} else {
				LOGGER.error("❌ BUG CONFIRMED: Grid NOT updated after save");
				LOGGER.error("Grid row count did not increase: initial={}, final={}", initialRowCount, finalRowCount);
				takeScreenshot("user-bug-grid-not-updated", true);
				
				// Check if user was actually saved by checking form field
				String savedName = nameField.inputValue();
				LOGGER.info("Form still shows name: {}", savedName);
			}
			
			LOGGER.info("=== User Create/Save/Grid Test Completed ===");
		} catch (Exception e) {
			LOGGER.error("❌ User test failed", e);
			takeScreenshot("user-test-error", true);
			throw new AssertionError("User test failed", e);
		}
	}
}
